def mostrar_menu():
    print("\n--- GERENCIADOR FINANCEIRO ---")
    print("1. Registrar Conta")
    print("2. Registrar Categoria")
    print("3. Registrar Transação")
    print("4. Exibir Contas")
    print("5. Exibir Categorias")
    print("6. Exibir Transações")
    print("7. Editar Contas")
    print("8. Editar Categorias")
    print("9. Editar Transações")
    print("10. Ver Total por Categoria")
    print("0. Sair")
